# Generated by Django 3.1.4 on 2020-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPM', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PojazdyWDokac',
            new_name='PojazdyWDokach',
        ),
        migrations.AddField(
            model_name='pojazdmiejski',
            name='wzrost',
            field=models.CharField(choices=[('dzieci', 'Dzieci'), ('dorośli', 'Dorosli')], default='dorośli', max_length=20),
        ),
    ]
